### ISSUE TITLE
Doesn't work with pre-existing multi-action service menus

### ISSUE THREAD

**Issue by cipricus** [Nyre221/dolphin-service-menus-creator#2]
I have read your comment on reddit [here](https://www.reddit.com/r/kde/comments/zheoc0/comment/izsdenf/?utm_source=share&utm_medium=web2x&context=3) saying that an update has fixed problems with some commands, and after updating a much severe problem is gone, where most of my pre-existing service menus were grayed out (and after a while none could be selected). 

The only problem I see now is that just 3 of my listed service menus are greyed out:

![image](https://user-images.githubusercontent.com/3447868/207088168-b98e204b-7190-4859-91d7-f28a756d0eba.png)

Maybe too big to post here, here they are on pastebin.

[pdf_ocr](https://pastebin.com/GDJEy2xx)
[pdf_shrink](https://pastebin.com/EGsNdreG)
[pdf_extract](https://pastebin.com/qwfHSu47)

From what I can tell, the names of the problematic service menus are seen wrongly: what is listed in the image above for "name" of the service menu "pdf_shrink" is just the name of the first of its actions.

It might very well be that the problem is related to the fact that all these are multi-action (multi-level) service menus, considering that I don't have others like them in this respect: the rest are single-action.

![image](https://user-images.githubusercontent.com/3447868/207093755-7b31c1d7-3687-42a9-ad9f-1cfa3dbaa84f.png)

**Comment by Nyre221** [comment]
Multi-action menus are not currently supported. I may add it in the future, but at the moment I don't intend to.
I've just started learning python and I don't have the skills to add this functionality now, and I want to study other things first without focusing too much on a single project.

Note: another missing feature is to use the name according to the system language, and therefore I don't recommend using it on your custom actions if you intend to publish them with multilingual support. Using this program in this case will delete the translations you have in your .desktop.

**Comment by cipricus** [comment]
Thank you. I have posted this just to clarify, and out of curiosity.

**Comment by cipricus** [comment]
Thank you. I have posted this just to clarify, and out of curiosity.

**Comment by Nyre221** [comment]
> Thank you. I have posted this just to clarify, and out of curiosity.

 @cipricus Thank you for reporting the issue 😃

Frankly, it amazes me that there is interest in this program. When I published it, I thought it would end up forgotten like the old service menu I did a while ago.

**Comment by cipricus** [comment]
> it amazes me that there is interest in this program

A tool like this is useful to those already interested in service menus and other detailed capabilities of Dolphin and such, but also to those that might start to learn. I have always liked Dolphin for its service menus, and I have a lot of them, but I know very little about CLI, the services I used are taken or made of parts taken from others, and I think the instructions included in your program might prove very useful to me in the future. I have other interests, learning coding is not my thing at all, but I cannot stand any non-Linux system anymore, I'm hooked. :)
